application: intersquares
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: .*
  script: main.py
